<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Untitled Page</title>
</head>
<body>

    <table style="width:100%;">
		<tr>
			<td colspan="2" 
                style="font-weight: bold;">
             <img src = '../../../Images/logo.png' style='height:70px;' /><br/>             
             <br/></td>
		</tr>
		<tr>
			<td align="center" colspan="2" 
                style="font-weight: bold; font-size:14pt;">
                CREATE E-MONEY
				<br/><br/>
			</td>
		</tr>
		<tr>
			<td>Transaction Number</td>
			<td>$TXREFID$</td>
        </tr>
        <tr>
			<td>Transaction Date</td>
			<td>$TXDT$</td>
        </tr>
        <tr>
			<td style="height:5px;">
			
			</td>
        </tr>
        <tr>
            <td colspan="2" 
                style="font-weight: bold; font-size:10pt;">
                E-MONEY INFOMATION<hr /></td>
        </tr>
		<tr>
            <td colspan="2" 
                style="font-weight: bold; font-size:8pt;">
                Debit Side<hr /></td>
        </tr>
		 <tr>
			<td>Base Account Number</td>
			<td>$BACNO_DEBIT$</td>
        </tr>
		<tr>
			<td>Account Name</td>
			<td>$ACNAME_DEBIT$</td>
        </tr>
		<tr>
			<td>Amount</td>
			<td>$AMOUNT_DEBIT$</td>
        </tr>
		<tr>
            <td colspan="2" 
                style="font-weight: bold; font-size:8pt;">
                Credit Side<hr /></td>
        </tr>
		 <tr>
			<th>Base Account Number</th>
			<th>Account Name</th>
			<th>Amount</th>
        </tr>
		<tr>
			<td>$BACNO_CREDIT$</td>
			<td>$ACNAME_CREDIT$</td>
			<td>$AMOUNT_CREDIT$</td>
		</tr>
		<tr>
			<td style="height:5px;">
			
			</td>
        </tr>
		<tr>
            <td colspan="2" 
                style="font-weight: bold; font-size:10pt;">
                MODIFICATION INFOMATION<hr /></td>
        </tr>
		<tr>
			<td>Date created</td>
			<td>$datecreated$</td>
        </tr>        
        <tr>
			<td>User created</td>
			<td>$usercreated$</td>
        </tr>
       <tr>
			<td colspan="2">
				<br/>
				<hr/>
				<p><a href='https://www.scb.co.th/en/personal-banking.html' target='blank'></a></p>
				<span style='font-weight:bold;'>
				Thank you for using services of Siam Commercial Bank!
				</span>
			</td>
		</tr>
    </table>

</body>
</html>
