<p>&nbsp;</p>
<table style="width: 100%;">
<tbody>
<tr>
<td style="font-weight: bold;" colspan="2"><img style="height: 70px;" src="../../../Images/logo.png" /><br /><br /></td>
</tr>
<tr>
<td style="font-weight: bold; font-size: 14pt;" colspan="2" align="center">ORDER FOR PAYMENT<br /><br /></td>
</tr>
<tr>
<td>Date time</td>
<td>$tranDate$</td>
</tr>
<tr>
<td>Transaction No</td>
<td>$tranID$</td>
</tr>
<tr>
<td style="height: 5px;">&nbsp;</td>
</tr>
<tr>
<td style="font-weight: bold; font-size: 10pt;" colspan="2">SENDER INFORMATION<hr /></td>
</tr>
<tr>
<td>Sender name</td>
<td>$senderName$</td>
</tr>
<tr>
<td>Debit account</td>
<td>$senderAccount$</td>
</tr>
<tr>
<td style="height: 5px;">&nbsp;</td>
</tr>
<tr>
<td style="height: 5px;">&nbsp;</td>
</tr>
<tr>
<td style="font-weight: bold; font-size: 10pt;" colspan="2">PAYMENT CONTENT<hr /></td>
</tr>
<tr>
<td>Amount</td>
<td>$amount$ $ccyid$</td>
</tr>
<tr>
<td>Amount in words</td>
<td>$amountchu$</td>
</tr>
<tr>
<td>Fee amount</td>
<td>$feeAmount$ $ccyid$</td>
</tr>
<tr>
<td>Payment content</td>
<td>$desc$</td>
</tr>
<tr>
<td colspan="2"><br /><hr /><span style="font-size: 8pt;"> Respond from the bank<br />Transaction no: $tranID$, status: $status$, at: $tranDate$</span>
<p><a href="https://www.scb.co.th/en/personal-banking.html" target="blank"></a></p>
<span style="font-weight: bold;"> Thank you for using ebanking services of Siam Commercial Bank! </span></td>
</tr>
</tbody>
</table>