<p>&nbsp;</p>
<div class="WordSection1">
	<table style="width: 100.0%; font-size: 10px;" border="0" width="100%" cellpadding="0">
		<tbody>
			<tr>
				<td style="padding: 0.75pt; width: 98.2955%;" colspan="4">
					<p class="MsoNormal" style="text-align: center;" align="center">
						<strong>
							<span style="font-size: 13.0pt; color: red;">WESTERN UNION TRANFERS</span>
						</strong>
					</p>
				</td>
			</tr>
			<tr>
				<td style="background:silver;background-color: #C0C0C0; line-height:13px;" colspan="4">
					<strong>INFORMATION FROM WESTERN UNION</strong>
				</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">MTCN</td>
				<td style="width: 24.5739%;" colspan="3">$CASHCODE$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">Transfer amount</td>
				<td style="width: 73.7216%;" colspan="3">$SENDERAMOUNT$ $SCCYID$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">Exchange rate amount:</td>
				<td style="width: 73.7216%;" colspan="3">$EXCHANGERATE$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">Transfer fee:</td>
				<td style="width: 73.7216%;" colspan="3">$FEEOFWU$ $SCCYID$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">Total Amount Receiver:</td>
				<td style="width: 73.7216%;" colspan="3">$REAMOUNT$ $RCCYID$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">Transfer Total:</td>
				<td style="width: 73.7216%;" colspan="3">$TOTAL$ $SCCYID$</td>
			</tr>
			<tr>
				<td style="line-height: 5px; width: 98.2955%;" colspan="4">&nbsp;</td>
			</tr>
			<tr>
				<td  style="background:silver;background-color: #C0C0C0; line-height:13px;" colspan="4">
					<strong>SENDER INFORMATION</strong>
				</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">First Name</td>
				<td style="width: 24.5739%;" colspan="4">$SENDERFIRSTNAME$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">Last Name</td>
				<td style="width: 24.5739%;" colspan="4">$SENDERLASTNAME$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">Sender Currency</td>
				<td style="width: 24.5739%;" colspan="4">$SCCYID$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">Payout Country</td>
				<td style="width: 24.5739%;" colspan="4">$PAYCOUNTRY$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">Amount to Send</td>
				<td style="width: 24.5739%;" colspan="4">$SENDERAMOUNT$ $SCCYID$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">Fee Amount</td>
				<td style="width: 24.5739%;" colspan="4">$FEE$ $SCCYID$</td>
			</tr>
			<tr>
				<td style="line-height: 5px; width: 98.2955%;" colspan="5">&nbsp;</td>
			</tr>
			<tr>
				<td  style="background:silver;background-color: #C0C0C0; line-height:13px;" colspan="4">
					<strong>SENDER DETAILS</strong>
				</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">Temporary Address - HouseNo/Unit</td>
				<td style="width: 24.5739%;" colspan="5">$SENDERUNIT$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">Temporary Address - Village/District</td>
				<td style="width: 24.5739%;" colspan="5">$SENDERDISTRICT$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">City</td>
				<td style="width: 24.5739%;" colspan="5">$SENDERCITY$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">State/Province</td>
				<td style="width: 24.5739%;" colspan="5">$SENDERPROVINCE$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">PostCode</td>
				<td style="width: 24.5739%;" colspan="5">$CASHCODE$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">Country</td>
				<td style="width: 24.5739%;" colspan="5">$SENDERCOUNTRY$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">Country Code</td>
				<td style="width: 24.5739%;" colspan="5">$COUNTRYCODE$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">Telephone number</td>
				<td style="width: 24.5739%;" colspan="5">$TELEPHONE$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">MB Country Code</td>
				<td style="width: 24.5739%;" colspan="5">$MOBILEPHONECODE$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">Mobile number</td>
				<td style="width: 24.5739%;" colspan="5">$PHONENO$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">Email</td>
				<td style="width: 24.5739%;" colspan="5">$EMAIL$</td>
			</tr>
			<tr>
				<td style="line-height: 5px; width: 98.2955%;" colspan="5">&nbsp;</td>
			</tr>
			<tr>
				<td  style="background:silver;background-color: #C0C0C0; line-height:13px;" colspan="4">
					<strong>ID DETAILS INFORMATION</strong>
				</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">ID TYPE</td>
				<td style="width: 24.5739%;" colspan="5">$ICTYPE$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">ID NUMBER</td>
				<td style="width: 24.5739%;" colspan="5">$ICNUMBER$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">COUNTRY OF ISSUE</td>
				<td style="width: 24.5739%;" colspan="5">$ISSUECOUNTRY$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">Expired Date</td>
				<td style="width: 24.5739%;" colspan="5">$EXDATE$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">Issue Date</td>
				<td style="width: 24.5739%;" colspan="5">$ISSUEDATE$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">Date of birth</td>
				<td style="width: 24.5739%;" colspan="5">$DATEOFBIRTH$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">Office Phone</td>
				<td style="width: 24.5739%;" colspan="5">$OFFICEPHONE$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">Occupation</td>
				<td style="width: 24.5739%;" colspan="5">$OCCUPATION$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">Purpose of Transaction</td>
				<td style="width: 24.5739%;" colspan="5">$PURPOSE$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">Source of Fund</td>
				<td style="width: 24.5739%;" colspan="5">$SOURCEOFUND$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">Permanent Address - HouseNo/Unit</td>
				<td style="width: 24.5739%;" colspan="5">$ICUNIT$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">Permanent Address - Village/District</td>
				<td style="width: 24.5739%;" colspan="5">$ICDISTRICT$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">Permanent Address - City/Province</td>
				<td style="width: 24.5739%;" colspan="5">$ICPROVINCE$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">Permanent Address - Country</td>
				<td style="width: 24.5739%;" colspan="5">$ICCOUNTRY$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">Country of Birth</td>
				<td style="width: 24.5739%;" colspan="5">$BIRTHCOUTRY$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">Nationality</td>
				<td style="width: 24.5739%;" colspan="5">$NATIONLITY$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">Gender</td>
				<td style="width: 24.5739%;" colspan="5">$GENDER$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">Comment</td>
				<td style="width: 24.5739%;" colspan="5">$COMMENT$</td>
			</tr>
			
			<tr>
				<td style="line-height: 5px; width: 98.2955%;" colspan="5">&nbsp;</td>
			</tr>
			<tr>
				<td  style="background:silver;background-color: #C0C0C0; line-height:13px;" colspan="4">
					<strong>RECEIVER INFORMATION</strong>
				</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">First Name</td>
				<td style="width: 24.5739%;" colspan="5">$REFIRSTNAME$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;"></td>
				<td style="width: 24.5739%;">Last Name</td>
				<td style="width: 24.5739%;" colspan="5">$RELASTNAME$</td>
			</tr>
		</tbody>
	</table>
</div>