//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Interfaces.wsChoLon {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getW_BillOperationCompleted;
        
        private System.Threading.SendOrPostCallback payW_BillOperationCompleted;
        
        private System.Threading.SendOrPostCallback checkPay_BillOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCustomerInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getW_Bill_EnOperationCompleted;
        
        private System.Threading.SendOrPostCallback payW_Bill_EnOperationCompleted;
        
        private System.Threading.SendOrPostCallback checkPayW_Bill_EnOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCustomerInfo_EnOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::Interfaces.Properties.Settings.Default.Interfaces_wsChoLon_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getW_BillCompletedEventHandler getW_BillCompleted;
        
        /// <remarks/>
        public event payW_BillCompletedEventHandler payW_BillCompleted;
        
        /// <remarks/>
        public event checkPay_BillCompletedEventHandler checkPay_BillCompleted;
        
        /// <remarks/>
        public event getCustomerInfoCompletedEventHandler getCustomerInfoCompleted;
        
        /// <remarks/>
        public event getW_Bill_EnCompletedEventHandler getW_Bill_EnCompleted;
        
        /// <remarks/>
        public event payW_Bill_EnCompletedEventHandler payW_Bill_EnCompleted;
        
        /// <remarks/>
        public event checkPayW_Bill_EnCompletedEventHandler checkPayW_Bill_EnCompleted;
        
        /// <remarks/>
        public event getCustomerInfo_EnCompletedEventHandler getCustomerInfo_EnCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getW_Bill", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getW_Bill(string danhba, string ten, string matkhau) {
            object[] results = this.Invoke("getW_Bill", new object[] {
                        danhba,
                        ten,
                        matkhau});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getW_BillAsync(string danhba, string ten, string matkhau) {
            this.getW_BillAsync(danhba, ten, matkhau, null);
        }
        
        /// <remarks/>
        public void getW_BillAsync(string danhba, string ten, string matkhau, object userState) {
            if ((this.getW_BillOperationCompleted == null)) {
                this.getW_BillOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetW_BillOperationCompleted);
            }
            this.InvokeAsync("getW_Bill", new object[] {
                        danhba,
                        ten,
                        matkhau}, this.getW_BillOperationCompleted, userState);
        }
        
        private void OngetW_BillOperationCompleted(object arg) {
            if ((this.getW_BillCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getW_BillCompleted(this, new getW_BillCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/payW_Bill", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool payW_Bill(string id, string ten, string matkhau) {
            object[] results = this.Invoke("payW_Bill", new object[] {
                        id,
                        ten,
                        matkhau});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void payW_BillAsync(string id, string ten, string matkhau) {
            this.payW_BillAsync(id, ten, matkhau, null);
        }
        
        /// <remarks/>
        public void payW_BillAsync(string id, string ten, string matkhau, object userState) {
            if ((this.payW_BillOperationCompleted == null)) {
                this.payW_BillOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpayW_BillOperationCompleted);
            }
            this.InvokeAsync("payW_Bill", new object[] {
                        id,
                        ten,
                        matkhau}, this.payW_BillOperationCompleted, userState);
        }
        
        private void OnpayW_BillOperationCompleted(object arg) {
            if ((this.payW_BillCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.payW_BillCompleted(this, new payW_BillCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/checkPay_Bill", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet checkPay_Bill(string id, string ten, string matkhau) {
            object[] results = this.Invoke("checkPay_Bill", new object[] {
                        id,
                        ten,
                        matkhau});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void checkPay_BillAsync(string id, string ten, string matkhau) {
            this.checkPay_BillAsync(id, ten, matkhau, null);
        }
        
        /// <remarks/>
        public void checkPay_BillAsync(string id, string ten, string matkhau, object userState) {
            if ((this.checkPay_BillOperationCompleted == null)) {
                this.checkPay_BillOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckPay_BillOperationCompleted);
            }
            this.InvokeAsync("checkPay_Bill", new object[] {
                        id,
                        ten,
                        matkhau}, this.checkPay_BillOperationCompleted, userState);
        }
        
        private void OncheckPay_BillOperationCompleted(object arg) {
            if ((this.checkPay_BillCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkPay_BillCompleted(this, new checkPay_BillCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCustomerInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getCustomerInfo(string danhba, string ten, string matkhau) {
            object[] results = this.Invoke("getCustomerInfo", new object[] {
                        danhba,
                        ten,
                        matkhau});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getCustomerInfoAsync(string danhba, string ten, string matkhau) {
            this.getCustomerInfoAsync(danhba, ten, matkhau, null);
        }
        
        /// <remarks/>
        public void getCustomerInfoAsync(string danhba, string ten, string matkhau, object userState) {
            if ((this.getCustomerInfoOperationCompleted == null)) {
                this.getCustomerInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCustomerInfoOperationCompleted);
            }
            this.InvokeAsync("getCustomerInfo", new object[] {
                        danhba,
                        ten,
                        matkhau}, this.getCustomerInfoOperationCompleted, userState);
        }
        
        private void OngetCustomerInfoOperationCompleted(object arg) {
            if ((this.getCustomerInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCustomerInfoCompleted(this, new getCustomerInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getW_Bill_En", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getW_Bill_En(string danhba, string ten, string matkhau) {
            object[] results = this.Invoke("getW_Bill_En", new object[] {
                        danhba,
                        ten,
                        matkhau});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getW_Bill_EnAsync(string danhba, string ten, string matkhau) {
            this.getW_Bill_EnAsync(danhba, ten, matkhau, null);
        }
        
        /// <remarks/>
        public void getW_Bill_EnAsync(string danhba, string ten, string matkhau, object userState) {
            if ((this.getW_Bill_EnOperationCompleted == null)) {
                this.getW_Bill_EnOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetW_Bill_EnOperationCompleted);
            }
            this.InvokeAsync("getW_Bill_En", new object[] {
                        danhba,
                        ten,
                        matkhau}, this.getW_Bill_EnOperationCompleted, userState);
        }
        
        private void OngetW_Bill_EnOperationCompleted(object arg) {
            if ((this.getW_Bill_EnCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getW_Bill_EnCompleted(this, new getW_Bill_EnCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/payW_Bill_En", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool payW_Bill_En(string id, string ten, string matkhau) {
            object[] results = this.Invoke("payW_Bill_En", new object[] {
                        id,
                        ten,
                        matkhau});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void payW_Bill_EnAsync(string id, string ten, string matkhau) {
            this.payW_Bill_EnAsync(id, ten, matkhau, null);
        }
        
        /// <remarks/>
        public void payW_Bill_EnAsync(string id, string ten, string matkhau, object userState) {
            if ((this.payW_Bill_EnOperationCompleted == null)) {
                this.payW_Bill_EnOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpayW_Bill_EnOperationCompleted);
            }
            this.InvokeAsync("payW_Bill_En", new object[] {
                        id,
                        ten,
                        matkhau}, this.payW_Bill_EnOperationCompleted, userState);
        }
        
        private void OnpayW_Bill_EnOperationCompleted(object arg) {
            if ((this.payW_Bill_EnCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.payW_Bill_EnCompleted(this, new payW_Bill_EnCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/checkPayW_Bill_En", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet checkPayW_Bill_En(string id, string ten, string matkhau) {
            object[] results = this.Invoke("checkPayW_Bill_En", new object[] {
                        id,
                        ten,
                        matkhau});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void checkPayW_Bill_EnAsync(string id, string ten, string matkhau) {
            this.checkPayW_Bill_EnAsync(id, ten, matkhau, null);
        }
        
        /// <remarks/>
        public void checkPayW_Bill_EnAsync(string id, string ten, string matkhau, object userState) {
            if ((this.checkPayW_Bill_EnOperationCompleted == null)) {
                this.checkPayW_Bill_EnOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckPayW_Bill_EnOperationCompleted);
            }
            this.InvokeAsync("checkPayW_Bill_En", new object[] {
                        id,
                        ten,
                        matkhau}, this.checkPayW_Bill_EnOperationCompleted, userState);
        }
        
        private void OncheckPayW_Bill_EnOperationCompleted(object arg) {
            if ((this.checkPayW_Bill_EnCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkPayW_Bill_EnCompleted(this, new checkPayW_Bill_EnCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCustomerInfo_En", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getCustomerInfo_En(string danhba, string ten, string matkhau) {
            object[] results = this.Invoke("getCustomerInfo_En", new object[] {
                        danhba,
                        ten,
                        matkhau});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getCustomerInfo_EnAsync(string danhba, string ten, string matkhau) {
            this.getCustomerInfo_EnAsync(danhba, ten, matkhau, null);
        }
        
        /// <remarks/>
        public void getCustomerInfo_EnAsync(string danhba, string ten, string matkhau, object userState) {
            if ((this.getCustomerInfo_EnOperationCompleted == null)) {
                this.getCustomerInfo_EnOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCustomerInfo_EnOperationCompleted);
            }
            this.InvokeAsync("getCustomerInfo_En", new object[] {
                        danhba,
                        ten,
                        matkhau}, this.getCustomerInfo_EnOperationCompleted, userState);
        }
        
        private void OngetCustomerInfo_EnOperationCompleted(object arg) {
            if ((this.getCustomerInfo_EnCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCustomerInfo_EnCompleted(this, new getCustomerInfo_EnCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getW_BillCompletedEventHandler(object sender, getW_BillCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getW_BillCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getW_BillCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void payW_BillCompletedEventHandler(object sender, payW_BillCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class payW_BillCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal payW_BillCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void checkPay_BillCompletedEventHandler(object sender, checkPay_BillCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkPay_BillCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkPay_BillCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getCustomerInfoCompletedEventHandler(object sender, getCustomerInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCustomerInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCustomerInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getW_Bill_EnCompletedEventHandler(object sender, getW_Bill_EnCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getW_Bill_EnCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getW_Bill_EnCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void payW_Bill_EnCompletedEventHandler(object sender, payW_Bill_EnCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class payW_Bill_EnCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal payW_Bill_EnCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void checkPayW_Bill_EnCompletedEventHandler(object sender, checkPayW_Bill_EnCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkPayW_Bill_EnCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkPayW_Bill_EnCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getCustomerInfo_EnCompletedEventHandler(object sender, getCustomerInfo_EnCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCustomerInfo_EnCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCustomerInfo_EnCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591