<!DOCTYPE html>
<html>

<head>
    <style>
        table,
        th,
        td {
            border: 1px solid black;
            border-collapse: collapse;
        }
        
        body {
            padding-top: 5px;
            padding-bottom: 5px;
            padding-right: 5px;
            padding-left: 5px;
            max-width: 95% !important;
            margin: auto;
        }
    </style>
</head>

<body>
    <h2 style="text-align: center;color:#28a745 !important">Terms of Use</h2>
    <p class="tx_indent"> &nbsp;&nbsp;&nbsp;&nbsp; It is important that you read these Terms of Use carefully as the following is a legally binding contract between YOU and THE SIAM COMMERCIAL BANK PUBLIC COMPANY LIMITED (the “Bank”) and governs your use of this website and the information provided herein. By using this website, you acknowledge that you have read and understood these Terms of Use, and that you agree to be bound by and comply with these Terms of Use. Do not use this website if you do not agree to be bound by these Terms of Use.
    </p>
    <h4 style="color:#28a745 !important">1. Agreement between You and the Bank</h4>
    <ul>
        <p class="tx_indent"> &nbsp;&nbsp;&nbsp;&nbsp; The Bank’s Website may contain various web pages operated by the Bank, with its head office located at 9 Ratchadapisek Road, Chatuchak, Bangkok 10900 (collectively, the "Bank’s Website"). The Bank’s Website is offered to you conditioned on your acceptance of these Terms of Use without modification. Your use of the Bank’s Website constitutes your legal binding agreement to all terms contained herein. If you do not agree to be bound by these Terms of Use, do not use the Bank’s Website.    
        </p>
    </ul>
    <h4 style="color:#28a745 !important"> 2. Modification of These Terms of Use</h4>
    <ul>
        <p class="tx_indent"> &nbsp;&nbsp;&nbsp;&nbsp; The Bank reserves the right to modify or alter these Terms of Use contained herein. You are responsible for regularly reviewing these Terms of Use and additional terms posted on the Bank’s Website. Your continued use of the Bank’s Website constitutes your agreement to such modified or altered terms of use.
        </p>
    </ul>
    <h4 style="color:#28a745 !important"> 3. Collection, Use and Disclosure of Personal Data </h4>
    <ul>
        <p class="tx_indent"> &nbsp;&nbsp;&nbsp;&nbsp; 
            For the use of the Bank’s services, the Bank will collect, use and disclose your personal data and/or any other person’s personal data provided by you to the Bank for the purpose of providing services and other purposes as prescribed in the Bank’s Privacy Notice. To understand how the Bank collects, uses and discloses personal data and the data owner’s rights in accordance with the Personal Data Protection Law, you may further read such Privacy Notice as announced by the Bank on the Bank’s website namely www.scb.co.th and/or any other channels prescribed by the Bank or to be further changed and notified to you by announcing on such website and/or any other channels prescribed by the Bank. In addition, in the event that you have given personal data of any other person, you shall notify such person of the details relating to the collection, use and disclosure of personal data and rights under such Privacy Notice.
        </p>
    </ul>    
    <h4 style="color:#28a745 !important"> 4. Links to Other Websites </h4>
    <ul>
        <p class="tx_indent"> &nbsp;&nbsp;&nbsp;&nbsp; 
            Links to other websites which are not under the control of the Bank may be arranged by the Bank for your information and convenience only. Any links executed by you to those websites shall be at your own risks. In no event shall the Bank be liable for any damages incurred by you in connection with the information, goods or services posted or offered on any third party's websites linked to the Bank’s Website. The Bank does not make any representation, warranty or recommendation in respect of any information, goods or services appearing in such third party's websites, nor shall the Bank be liable for any defects or breaches of contracts in respect of any goods or services appearing or advertising in those websites. The Bank does not have any commitments or agreements with such other websites in connection with your agreements with such other websites.
            </p>
        <p class="tx_indent"> &nbsp;&nbsp;&nbsp;&nbsp;     Any link to other websites for downloading any software are provided by the Bank for your convenience only. In no event shall the Bank be responsible or liable for any error or malfunction caused by or resulted from the downloaded software. Be aware that any use of the downloaded software shall be subject to the terms and conditions of the relevant license agreement. Should you be unable to comply with such license agreement, you may be deemed as an infringer of copyright or other intellectual property rights of such software provider. In such event, the Bank shall not be liable for any damages incurred by you in all respects. Please also note that whenever you link to any of such other websites, you will be subject to the terms, conditions and policies of using the websites being visited by you.
        </p>
    </ul>
    <h4 style="color:#28a745 !important">5. Indemnity</h4>
    <ul>
        <p class="tx_indent"> &nbsp;&nbsp;&nbsp;&nbsp; 
            You hereby agree to indemnify the Bank against any claims, losses, costs and damages (including legal fees and court costs) suffered or incurred by the Bank as a result of your improper use of the Bank’s Website or any use in violation of these Terms of Use.
        </p>
    </ul>
    <h4 style="color:#28a745 !important">6. Trademarks, Service Marks, Copyright and other Intellectual Property Rights</h4>
    <ul>
        <p class="tx_indent"> &nbsp;&nbsp;&nbsp;&nbsp; 
            Any data and information contained or displayed in the Bank’s Website are the properties of the Bank and the third parties (as the case may be). All trademarks, service marks, trade names and logos mentioned in or posted on the Bank’s Website (collectively the "Trademarks") shall include any trademarks, service marks and logos of the Bank and any third parties regardless of whether such trademarks, service marks and logos have been registered or not.
            </p>
            <p class="tx_indent"> &nbsp;&nbsp;&nbsp;&nbsp; No part or parts hereof shall be deemed as a license or a granting of the right to use such Trademarks. The Bank hereby reserves all rights it may have in connection with this Website. The Bank does not allow or grant any right to use Trademarks without obtaining a prior written consent from the Bank or the third party (as the case may be). The Bank’s Website is protected under copyright and intellectual property laws and shall not be modified, reproduced, copied, downloaded, transmitted (in any form and by any means) or used in whatever manner for commercial purposes without obtaining a prior written consent from the Bank.
    </p>
    </ul>
    <h4 style="color:#28a745 !important">7. Termination, Access Restriction and Prohibited Use</h4>
    <ul>
        <p class="tx_indent"> &nbsp;&nbsp;&nbsp;&nbsp; 
            The Bank reserves the right, at its sole discretion, to terminate this agreement or your access to the Bank’s Website and the related services at any time without prior notice, if you fail to comply with these Terms of Use or for any reason deemed necessary by the Bank.
            </p>
            <p class="tx_indent"> &nbsp;&nbsp;&nbsp;&nbsp; You shall not use the Bank’s Website for any purpose that is unlawful or prohibited by laws and these Terms of Use and in any manner that could damage, disable, or impair the Bank’s Website or the networks connected to the Bank’s Website. You shall not interfere with any other party's use and enjoyment of the Bank’s Website and not attempt to gain unauthorized access to the Bank’s Website, other accounts, computer systems or networks connected to the Bank’s Website, through hacking, password mining or any other means.
        </p>
    </ul>
    <h4 style="color:#28a745 !important">8. Liability Disclaimer</h4>
    <ul>
        <p class="tx_indent"> &nbsp;&nbsp;&nbsp;&nbsp; 
            THE INFORMATION, PRODUCTS AND SERVICES INCLUDED IN OR AVAILABLE THROUGH THE BANK’S WEBSITE MAY INCLUDE INACCURACIES OR TYPOGRAPHICAL ERRORS. THE BANK RESERVES ITS RIGHT TO MODIFY OR MAKE CHANGES TO THE BANK’S WEBSITE AND THE INFORMATION CONTAINED THEREIN WITHOUT PRIOR NOTICE. ANY INFORMATION RECEIVED VIA THE BANK’S WEBSITE SHOULD NOT BE RELIED UPON FOR PERSONAL, LEGAL OR FINANCIAL DECISIONS AND YOU SHOULD CONSULT AN APPROPRIATE PROFESSIONAL FOR SPECIFIC ADVICE TAILORED TO YOUR SITUATION.
            </p>
            <p class="tx_indent"> &nbsp;&nbsp;&nbsp;&nbsp; THE BANK MAKES NO REPRESENTATION OR WARRANTY OF ANY KIND, EITHER EXPLICITLY OR IMPLICITLY, AS TO THE SUITABILITY, RELIABILITY, AVAILABILITY, TIMELINESS, LACK OF VIRUSES OR OTHER HARMFUL COMPONENTS, AND ACCURACIES OF THE INFORMATION, SOFTWARE, PRODUCTS AND RELATED GRAPHICS CONTAINED WITHIN THE BANK’S WEBSITE FOR ANY PURPOSES. THE BANK ACCEPTS NO LIABILITY AND WILL NOT BE LIABLE FOR ANY LOSS OR DAMAGE ARISING DIRECTLY OR INDIRECTLY (INCLUDING SPECIAL, INCIDENTAL OR CONSEQUENTIAL LOSS OR DAMAGE) FROM YOUR USE OF THE BANK’S WEBSITE. IN PARTICULAR, NO WARRANTY IS GIVEN THAT ECONOMIC REPORTING INFORMATION MATERIAL OR DATA IS ACCURATE, COMPLETE AND/OR UP TO DATE.
            </p>
            <p class="tx_indent"> &nbsp;&nbsp;&nbsp;&nbsp; YOU AGREE THAT THE BANK SHALL NOT BE RESPONSIBLE OR LIABLE FOR UNAUTHORIZED ACCESS TO YOUR DATA OR TRANSACTIONS ON THE BANK’S WEBSITE.</p>
    </ul>
    <h4 style="color:#28a745 !important">9. Governing Law</h4>
    <ul>
        <p class="tx_indent"> &nbsp;&nbsp;&nbsp;&nbsp; 
            These Terms of Use are governed by the laws of the Kingdom of Thailand. Any disputes shall be subject to the non-exclusive jurisdiction of the Courts of Thailand. You agree that no joint venture, partnership, employment or agency relationship exists between you and the Bank as a result of this agreement or your use of the Bank’s Website.
        </p>
    </ul>
</body>

</html>