<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Untitled Page</title>
</head>
<body>

    <table style="width:100%;">
        <tr>
            <td align="center" colspan="4" 
                style="font-weight: bold; font-size: large; color: #FF0000">
                CONTRACT INFOMATION<hr /></td>
        </tr>
        <tr>
            <td colspan="4" style="font-weight: bold; background-color: #C0C0C0;">
                CUSTOMER DETAIL</td>
        </tr>
        <tr>
            <td>
                Customer code :</td>
            <td>
                $CUSTID$</td>
            <td>
                Fullname :</td>
            <td>
                $FULLNAME$</td>
        </tr>
        <tr>
            <td>
                Customer type :</td>
            <td>
                $CUSTTYPE$</td>
            <td>
                Phone :</td>
            <td>
                $PHONE$</td>
        </tr>
        <tr>
            <td>
                Email :</td>
            <td>
                $EMAIL$</td>
            <td>
                &nbsp;</td>
            <td>
                &nbsp;</td>
        </tr>
        <tr>
            <td colspan="4" style="font-weight: bold; background-color: #C0C0C0;">
                CONTRACT DETAIL</td>
        </tr>
        <tr>
            <td>
                Contract no :</td>
            <td>
                $CONTRACTNO$</td>
            <td>
                Contract type :</td>
            <td>
                $CONTRACTTYPE$</td>
        </tr>
        <tr>
            <td>
                Open date :</td>
            <td>
                $OPENDATE$</td>
            <td>
                Expire date :</td>
            <td>
                $ENDDATE$</td>
        </tr>
        <tr>
            <td>
                Product :</td>
            <td>
                $PRODUCT$</td>
            <td>
                &nbsp;</td>
            <td>
                &nbsp;</td>
        </tr>
        <tr>
            <td colspan="4" style="font-weight: bold; background-color: #C0C0C0;">
                ACCOUNT DETAIL</td>
        </tr>
        <tr>
            <td colspan="4">
                $USERINFO$</td>
            
        </tr>
       
    </table>

</body>
</html>
