<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Untitled Page</title>
</head>
<body>

    <table style="width:100%;">
		<tr>
			<td colspan="4" 
                style="font-weight: bold;">
             <img src = '../../../Images/logo.png' /><br/>             
             <br/></td>
		</tr>
        </table>
        <table style="width:100%;">
        <tr>
			<td align="center" colspan="4" 
                style="font-weight: bold; font-size:14pt;">
                THÔNG TIN DUYỆT TẤT TOÁN TÀI KHOẢN TIẾT KIỆM<br/><br/></td>
		</tr>
        <tr>
				<td colspan="4" 
                style="font-weight: bold; font-size:10pt;">
                Chi tiết giao dịch<hr /></td>

        </tr>
        <tr>
			<td>Số giao dịch</td>
			<td>$sogiaodich$</td>
			<td>Ngày giờ giao dịch</td>
			<td>$ngaygiogiaodich$</td>
        </tr>
        <tr>

        </tr>
                <tr>
				<td colspan="4" 
                style="font-weight: bold; font-size:10pt;">
                Thông tin tài khoản tiết kiệm<hr /></td>

        </tr>
        <tr>
			<td>Tài khoản tiết kiệm có kỳ hạn</td>
			<td>$taikhoantietkiemcokyhan$</td>
			<td>Số dư hiện tại</td>
			<td>$soduhientai$ </td>
        </tr>
        <tr>

        </tr>
        <tr>
			<td>Ngày mở tài khoản</td>
			<td>$ngaymotaikhoan$</td>
			<td>Lãi suất</td>
			<td>$laisuat$</td>
        </tr>
        <tr>

        </tr>
        <tr>
			<td>Ngày đến hạn</td>
			<td>$ngaydenhan$</td>
			<td>Tên tài khoản</td>
			<td>$tentaikhoan$</td>
        </tr>
        <tr>
			<td>Chi nhánh</td>
			<td>$chinhanhfd$</td>
			<td></td>
			<td></td>
        </tr>
        <tr>

        </tr>
                </tr>
        <tr>
				<td colspan="4" 
                style="font-weight: bold; font-size:10pt;">
                Thông tin tài khoản thanh toán<hr /></td>

        </tr>
        <tr>
			<td>Tài khoản thanh toán</td>
			<td>$taikhoanthanhtoan$</td>
			<td>Chi nhánh</td>
			<td>$chinhanh$</td>
        </tr>  
        <tr>

        </tr>
        <tr>
				<td colspan="4" 
                style="font-weight: bold; font-size:10pt;">
                Thông tin giao dịch<hr /></td>

        </tr>
        <tr>
			<td>Số tiền</td>
			<td>$sotien$ </td>
			<td>Mô tả</td>
			<td>$mota$</td>
        </tr>
        <tr>

        </tr>
        <tr>
			<td>Tên khách hàng</td>
			<td>$tenkhachhang$</td>
			<td>Người duyệt</td>
			<td>$nguoiduyet$</td>
        </tr>
        <tr>

        </tr>
        <tr>
			<td>Trạng thái</td>
			<td>$trangthai$</td>
        </tr>
        <tr>
				<td colspan="4" 
                style="font-weight: bold; font-size:10pt;">
                Chi tiết duyệt giao dịch<hr /></td>

        </tr>
    </table>
	
	$thongtinchitietduyet$
	
	<table style="width:100%;">
	    <tr>
				<td colspan="4" 
                style="font-weight: bold; font-size:10pt;">
                Thông tin duyệt giao dịch<hr /></td>

        </tr>
        <tr>
			<td style="width:30%;">Lãi được hưởng tạm tính</td>
			<td style="width:22%;">$laiduochuongtamtinh$</td>
			<td style="width:20%;">Lãi cộng dồn</td>
			<td style="width:30%;">$laicongdon$</td>
        </tr>  
        <tr>

        </tr>
         <tr>
			<td>Diễn giải</td>
			<td>$diengiai$</td>
			<td></td>
			<td></td>
        </tr>
    </table>
	<table style="width:100%;">
       <tr>
			<td colspan="4">
				<br/>
				<p><a href='https://www.scb.co.th/en/personal-banking.html' target='blank'></a></p>
				<span style='font-weight:bold;'>
				Cảm ơn quý khách đã sử dụng dịch vụ ebanking của Siam Commercial Bank!
				</span>
			</td>
		</tr>
    </table>

</body>
</html>
