<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Internet Banking - LAOS FOREIGN TRADE BANK</title>
</head>
<body>

    <table style="width:100%;">
		<tr>
			<td colspan="2" style="font-weight: bold;">
             <img src='https://upload.wikimedia.org/wikipedia/en/thumb/4/47/Siam_Commercial_Bank_%28logo%29.svg/345px-Siam_Commercial_Bank_%28logo%29.svg.png' style='height:70px;' /><br/>             
             <br/>
            </td>
		</tr>
		<tr>
			<td align="center" colspan="2" 
                style="font-weight: bold; font-size:14pt;">
                ORDER FOR PAYMENT<br/><br/></td>
		</tr>
		<tr>
			<td>Date time</td>
			<td>$tranDate$</td>
        </tr>
        <tr>
			<td>Transaction No</td>
			<td>$tranID$</td>
        </tr>
        <tr>
			<td style="height:5px;" colspan="2">
			
			</td>
        </tr>
        <tr>
            <td colspan="2" 
                style="font-weight: bold; font-size:10pt;">
                SENDER INFORMATION<hr /></td>
        </tr>
        <tr>
			<td>Sender name</td>
			<td>$senderName$</td>
        </tr>
        <tr>
			<td>Debit account</td>
			<td>$senderAccount$</td>
        </tr>        
        
        <tr>
			<td style="height:5px;" colspan="2">
			
			</td>
			
        </tr>
        <tr>
            <td colspan="2" 
                style="font-weight: bold; font-size:10pt;">
                SERVICE<hr /></td>
        </tr>
        <tr>
			<td>Provider</td>
			<td>$recieverName$</td>
        </tr>
        <tr>
			<td>Credit account</td>
			<td>$recieverAccount$</td>
        </tr>        
        
        
        <tr>
			<td style="height:5px;">
			
			    Payment content</td>
			<td style="height:5px;">
			
			    $desc$</td>
        </tr>
        <tr>
            <td colspan="2" 
                style="font-weight: bold; font-size:10pt;">
                PAYMENT INFORMATION<hr /></td>
        </tr>
        
        <tr>
			<td>Amount</td>
			<td>$amount$ $ccyid$</td>
        </tr>
        <tr>
			<td>Amount in words</td>
			<td>$amountchu$</td>
        </tr>
        <tr>
			<td>Fee payment by</td>
			<td>$feeType$</td>
        </tr>
        <tr>
			<td>Fee amount</td>
			<td>$feeAmount$ $ccyid$</td>
        </tr>
        <tr>
			<td colspan="2">
				<table style="width:100%;margin-bottom:30px;margin-top:15px;">
					<tr>
						
					</tr>
				</table>
			</td>
		</tr>
       <tr>
			<td colspan="2">
				<br/>
				<hr/>
				<p><a href='https://www.phongsavanhbank.com/' target='blank'>https://phongsavanhbank.com/</a></p>
				<span style='font-weight:bold;'>
				Thank you for using services of LAOS FOREIGN TRADE BANK
				
                
                </span>
            </td>
        </tr>
    </table>
</body>
</html>
