<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">https://upload.wikimedia.org/wikipedia/en/thumb/4/47/Siam_Commercial_Bank_%28logo%29.svg/345px-Siam_Commercial_Bank_%28logo%29.svg.png
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
<style type="text/css">
<!--
.style1 {
	color: #0066CC;
	font-weight: bold;
	font-size: 24px;
}
.style2 {
	color: #0099FF;
	font-weight: bold;
}
.style3 {color: #0066CC}
-->
</style>
</head>

<body>
<table width="100%" height="200px" border="0">
  <tr>
    <td colspan="3"><p>&nbsp;</p>
    <p>&nbsp;</p></td>
  </tr>
  <tr>
    <td style="width:20%">&nbsp;</td>
     <td style="width:60%"><table width="100%" border="0">
       <tr>
         <td width="271"><img src="https://upload.wikimedia.org/wikipedia/en/thumb/4/47/Siam_Commercial_Bank_%28logo%29.svg/345px-Siam_Commercial_Bank_%28logo%29.svg.png" alt="logo" width="150" height="70" /></td>
         <td width="281"><div align="center"><span class="style3">279 Lý Thường Kiệt, Phường 15, Quận 11, TP.HCM, Việt Nam - Điện thoại: (84 8)   3866.3890 - Fax: (84 8) 3866.3891</span><br />
         </div></td>
       </tr>
     </table>
       <div style="width:100%; height:2px; background:#990000; margin-top:15px;"> </div>
       <p><span class="usertext"><span class="style1">NGÂN HÀNG Phongsavanh</span></span> <br />
            <span class="usertext style2"><br />
         <span class="style3">THÔNG TIN MẬT KHẨU</span></span> </p>
       <p><span class="usertext"> <span class="style3">Kính chào: <strong>$FULLNAME$</strong><br /> <br />
         Tên đăng nhập: <strong>$USER$</strong>.<br />
         <br />
         Chúng tôi nhận đươc yêu cầu lấy lại mật khẩu của quý khách 
         cho dich vu Internet Banking<br /><br />
         <strong>Mật khẩu mới của quý khách là : 
         $PASS$</strong></span><br />
    <br />
         <em>Xin chân thành cảm ơn quý khách đã sử dụng dịch vụ 
     Ebanking của Phongsavanh!</em> </span></p></td>
     <td style="width:20%">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="3">&nbsp;</td>
  </tr>
</table>
<p>&nbsp;</p>
<p>&nbsp;</p>
</body>
</html>
