<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Untitled Page</title>
</head>
<body>

    <table style="width:100%;">
		<tr>
			<td colspan="2" 
                style="font-weight: bold;">
             <img src = '../../../Images/logo.png' style='height:70px;' /><br/>             
             <br/></td>
		</tr>
		<tr>
			<td align="center" colspan="2" 
                style="font-weight: bold; font-size:14pt;">
                TOP-UP E-WALLET<br/><br/></td>
		</tr>
		<tr>
			<td>Transaction Number</td>
			<td>$TXREFID$</td>
        </tr>
        <tr>
			<td>Transaction Date</td>
			<td>$TXDT$</td>
        </tr>
        <tr>
			<td style="height:5px;">
			
			</td>
        </tr>
        <tr>
            <td colspan="2" 
                style="font-weight: bold; font-size:10pt;">
                TOP-UP INFORMATION<hr /></td>
        </tr>
		<tr>
			<td>Phone Number</td>
			<td>$PHONE_NUMBER$</td>
        </tr>
        <tr>
			<td>Full Name</td>
			<td>$FULL_NAME$</td>
        </tr>
		<tr>
			<td>Amount</td>
			<td>$AMOUNT$</td>
        </tr>
		<tr>
			<td>Bonus</td>
			<td>$BONUS_AMOUNT$</td>
        </tr>
		<tr>
			<td>Fee</td>
			<td>$FEE_AMOUNT$</td>
        </tr>
        <tr>
			<td>Currency</td>
			<td>$CCYID$</td>
        </tr>
		<tr>
			<td>Previous Main Wallet</td>
			<td>$PREVIOUS_BALANCE$</td>
        </tr>
        <tr>
			<td>Main Wallet</td>
			<td>$BALANCE$</td>
        </tr>   
		<tr>
			<td>Previous Coin Wallet</td>
			<td>$PREVIOUS_COIN$</td>
        </tr>
        <tr>
			<td>Coin Wallet</td>
			<td>$CoinWallet$</td>
        </tr>  
        <tr>
			<td>Description</td>
			<td>$desc$</td>
        </tr>
		<tr>
			<td style="height:5px;">
			
			</td>
        </tr>
		<tr>
            <td colspan="2" 
                style="font-weight: bold; font-size:10pt;">
                MODIFICATION INFORMATION<hr /></td>
        </tr>
		<tr>
			<td>Date created</td>
			<td>$datecreated$</td>
        </tr>        
        <tr>
			<td>User created</td>
			<td>$usercreated$</td>
        </tr>
       <tr>
			<td colspan="2">
				<br/>
				<hr/>
				<p><a href='https://www.scb.co.th/en/personal-banking.html' target='blank'></a></p>
				<span style='font-weight:bold;'>
				Thank you for using services of Siam Commercial Bank!
				</span>
			</td>
		</tr>
    </table>

</body>
</html>
