<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Untitled Page</title>
</head>
<body>

    <table style="width:100%;">
		<tr>
			<td colspan="2" 
                style="font-weight: bold;">
             <img src='https://ib.hellomoney.com.la:9004/Images/logo.png' style='height:70px;' /><br/>             
             <br/></td>
		</tr>
		<tr>
			<td align="center" colspan="2" 
                style="font-weight: bold; font-size:14pt;">
                ORDER FOR PAYMENT<br/><br/></td>
		</tr>
		<tr>
			<td>Date time</td>
			<td>$tranDate$</td>
        </tr>
        <tr>
			<td>Transaction No</td>
			<td>$tranID$</td>
        </tr>
        <tr>
			<td style="height:5px;">
			
			</td>
        </tr>
        <tr>
            <td colspan="2" 
                style="font-weight: bold; font-size:10pt;">
                SENDER INFORMATION<hr /></td>
        </tr>
        <tr>
			<td>Sender name</td>
			<td>$senderName$</td>
        </tr>
        <tr>
			<td>Debit account</td>
			<td>$senderAccount$</td>
        </tr>
		<tr>
			<td>Payout Country</td>
			<td>$PAYCOUNTRY$</td>
        </tr>
		<tr>
			<td>Temporary Address - HouseNo/Unit</td>
			<td>$SENDERUNIT$</td>
        </tr>
		<tr>
			<td>Temporary Address - Village/District</td>
			<td>$SENDERDISTRICT$</td>
        </tr>
		<tr>
			<td>City</td>
			<td>$SENDERCITY$</td>
        </tr>
		<tr>
			<td>State/Province</td>
			<td>$SENDERPROVINCE$</td>
        </tr>
		<tr>
			<td>PostCode</td>
			<td>$POSTCODE$</td>
        </tr>
		<tr>
			<td>Country</td>
			<td>$SENDERCOUNTRY$</td>
        </tr>
		<tr>
			<td>Country Code</td>
			<td>$COUNTRYCODE$</td>
        </tr>
		<tr>
			<td>Telephone number</td>
			<td>$TELEPHONE$</td>
        </tr>
		<tr>
			<td>MB Country Code</td>
			<td>$MOBILEPHONECODE$</td>
        </tr>
		<tr>
			<td>Mobile number</td>
			<td>$PHONENO$</td>
        </tr>
		<tr>
			<td>Email</td>
			<td>$EMAIL$</td>
        </tr>

        <tr>
			<td style="height:5px;">

			</td>
        </tr>

		<tr>
            <td colspan="2" 
                style="font-weight: bold; font-size:10pt;">
                ID DETAILS<hr /></td>
        </tr>
        <tr>
			<td>ID TYPE</td>
			<td>$ICTYPE$</td>
        </tr>
        <tr>
			<td>ID NUMBER</td>
			<td>$ICNUMBER$</td>
        </tr>
		<tr>
			<td>COUNTRY OF ISSUE</td>
			<td>$ISSUECOUNTRY$</td>
        </tr>
        <tr>
			<td>Expired Date</td>
			<td>$EXDATE$</td>
        </tr>
		<tr>
			<td>Issue Date</td>
			<td>$ISSUEDATE$</td>
        </tr>
        <tr>
			<td>Date of birth</td>
			<td>$DATEOFBIRTH$</td>
        </tr>
		<tr>
			<td>Office Phone</td>
			<td>$OFFICEPHONE$</td>
        </tr>
		<tr>
			<td>Occupation</td>
			<td>$OCCUPATION$</td>
        </tr>
        <tr>
			<td>Purpose of Transaction</td>
			<td>$PURPOSE$</td>
        </tr>
		<tr>
			<td>Source of Fund</td>
			<td>$SOURCEOFUND$</td>
        </tr>
		<tr>
			<td>Permanent Address - HouseNo/Unit</td>
			<td>$ICUNIT$</td>
        </tr>
		<tr>
			<td>Permanent Address - Village/District</td>
			<td>$ICDISTRICT$</td>
        </tr>
		<tr>
			<td>Permanent Address - City/Province</td>
			<td>$ICPROVINCE$</td>
        </tr>
		<tr>
			<td>Permanent Address - Country</td>
			<td>$ICCOUNTRY$</td>
        </tr>
		<tr>
			<td>Country of Birth</td>
			<td>$BIRTHCOUTRY$</td>
        </tr>
		<tr>
			<td>Nationality</td>
			<td>$NATIONLITY$</td>
        </tr>
		<tr>
			<td>Gender</td>
			<td>$GENDER$</td>
        </tr>
		<tr>
			<td>Comment</td>
			<td>$COMMENT$</td>
        </tr>
		<tr>
			<td>File Upload</td>
			<td>$FILE$</td>
        </tr>
        <tr>
			<td style="height:5px;">
			
			</td>
        </tr>

        <tr>
            <td colspan="2" 
                style="font-weight: bold; font-size:10pt;">
                RECEIVER INFORMATION<hr /></td>
        </tr>
        <tr>
			<td>Receiver first name</td>
			<td>$receiverFirstName$</td>
        </tr>
        <tr>
			<td>Receiver last name</td>
			<td>$receiverLastName$</td>
        </tr>
        <tr>
			<td style="height:5px;">
			
			</td>
        </tr>
        <tr>
            <td colspan="2" 
                style="font-weight: bold; font-size:10pt;">
                PAYMENT CONTENT<hr /></td>
        </tr>
        
        <tr>
			<td>Transfer amount</td>
			<td>$amount$ $ccyid$</td>
        </tr>
        <tr>
			<td>Fee payment by</td>
			<td>$feeType$</td>
        </tr>
        <tr>
			<td>Fee amount</td>
			<td>$feeAmount$ $ccyid$</td>
        </tr>
		<tr>
			<td>Transfer total</td>
			<td>$transtotal$ $ccyid$</td>
        </tr>
		
        <!--<tr>
			<td colspan="2">
				<table style="width:100%;margin-bottom:30px;margin-top:15px;">
					<tr>
						
					</tr>
				</table>
			</td>
		</tr>--!>
       <tr>
			<td colspan="2">
				<br/>
				<hr/>
				<span style='font-size:8pt;'>
				Respond from the bank<br/>
				Transaction no: $tranID$, status: $status$, at: $tranDate$</span>
				<p><a href='https://www.scb.co.th/en/personal-banking.html' target='blank'>www.scb.co.th/en/personal-banking</a></p>
				<span style='font-weight:bold;'>
				Thank you for using Siam Commercial Bank!
				</span>
			</td>
		</tr>
    </table>

</body>
</html>
