<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Untitled Page</title>
</head>
<body>

    <table style="width:100%;">
		<tr>
			<td colspan="2" 
                style="font-weight: bold;">
             <img src='https://upload.wikimedia.org/wikipedia/en/thumb/4/47/Siam_Commercial_Bank_%28logo%29.svg/345px-Siam_Commercial_Bank_%28logo%29.svg.png' style='height:70px;' /><br/>             
             <br/></td>
		</tr>
		<tr>
			<td align="center" colspan="2" 
                style="font-weight: bold; font-size:14pt;">
                SHOP INFORMATION<br/><br/></td>
		</tr>
        <tr>
            <td colspan="2" 
                style="font-weight: bold; font-size:10pt;">
                CONTRACT INFORMATION<hr /></td>
        </tr>
        <tr>
			<td>Contract Number</td>
			<td>$ContractNo$</td>
        </tr>
        <tr>
			<td style="height:5px;">
			
			</td>
        </tr>
        <tr>
            <td colspan="2" 
                style="font-weight: bold; font-size:10pt;">
                SHOP INFORMATION<hr /></td>
        </tr>
        <tr>
			<td>Shop ID</td>
			<td>$ShopID$</td>
        </tr>
        <tr>
			<td>Shop name</td>
			<td>$ShopName$</td>
        </tr>        
        <tr>
			<td>Shop code</td>
			<td>$ShopCode$</td>
        </tr>
        <tr>
			<td>Email</td>
			<td>$Email$</td>
        </tr>
        <tr>
			<td>Phone number</td>
			<td>$PhoneNo$</td>
        </tr>        
        <tr>
			<td style="height:5px;">
			
			</td>
        </tr>
        <tr>
            <td colspan="2" 
                style="font-weight: bold; font-size:10pt;">
                ACCOUNT INFO<hr /></td>
        </tr>
        
        <tr>
			<td>Shop account</td>
			<td>$AcctNo$</td>
        </tr>
        <tr>
			<td>Suspend account</td>
			<td>$SuspendAcctNo$</td>
        </tr>
        <tr>
			<td>Incom account</td>
			<td>$IncomAcctNo$</td>
        </tr>
        <tr>
			<td style="height:5px;">
			
			</td>
        </tr>
        <tr>
            <td colspan="2" 
                style="font-weight: bold; font-size:10pt;">
                SECURITY INFO<hr /></td>
        </tr>
        
        <tr>
			<td>Public key</td>
			<td>$Password$</td>
        </tr>
        <tr>
			<td>Secret code</td>
			<td>$SecretCode$</td>
        </tr>
       <tr>
			<td colspan="2">
				<br/>
				<hr/>
				<span style='font-size:8pt;'>
				Respond from the bank<br/>
				Transaction no: $tranID$, status: $status$, at: $tranDate$</span>
				<p><a href='https://www.scb.co.th/en/personal-banking.html' target='blank'>www.scb.co.th/en/personal-banking</a></p>
				<span style='font-weight:bold;'>
				Thank you for using Siam Commercial Bank!
				</span>
			</td>
		</tr>
    </table>

</body>
</html>

