<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Untitled Page</title>
	<style type="text/css">
		.style1 {
			width: 100%;
			border: 1px solid rgb(204, 204, 204);
		}
		.thtdf {
			background-color: #7A58BF;
			border: 1px solid #ccc;
			padding: 5px 10px;
		}
		.trtd td {
			border: 1px solid #ccc;
			padding: 5px 10px;
		}
	</style>
</head>
<body>

    <table style="width:100%;" cellspacing="5">
		<tr>
			<td colspan="4" 
                style="font-weight: bold;">
             <img src='https://upload.wikimedia.org/wikipedia/en/thumb/4/47/Siam_Commercial_Bank_%28logo%29.svg/345px-Siam_Commercial_Bank_%28logo%29.svg.png' style='height:70px;' /><br/>             
             <br/></td>
		</tr>
		<tr>
			<td align="center" colspan="4" 
                style="font-weight: bold; font-size:14pt;">
                CANCEL TRANSACTION<br/><br/></td>
		</tr>

		<tr>
            <td colspan="4">
                Transaction <b>$tranID$</b> you approved has been canceled.
        </tr>
       <tr>
			<td colspan="4">
				<br/>
				<span style='font-size:8pt;'>
				Respond from the bank<br/>
				Transaction no: $tranID$ at: $date$</span>
				<p><a href='https://www.scb.co.th/en/personal-banking.html' target='blank'>www.scb.co.th/en/personal-banking</a></p>
				<span style='font-weight:bold;'>
				Thank you for using Siam Commercial Bank!
				</span>
			</td>
		</tr>
    </table>

</body>
</html>
