<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Untitled Page</title>

<style type="text/css">
<!--
.style1 {
	color: #0033FF;
	font-weight: bold;
}
.style2 {
	font-size: 18px;
	font-weight: bold;
}
-->
</style>
</head>

<body>
<p class="style1">Siam Commercial Bank</p>

    <table style="width:100%;">
       <tr>
            <td align="center" colspan="4" 
                style="font-weight: bold; font-size: 11pt; color: #FF0000">
               REJECT INFORMATION PINCODE<hr /></td>
        </tr>
        <tr>
            <td colspan="4">
            We would like to inform you that your reset pincode request for user <b> $USERNAME$ </b> have rejected by Siam Commercial's operator due missing or incorrect account information <br />
            Please submit request with correct information again or contact support center for more detail.

        </td>
            
        </tr>
                <tr>
            <td colspan="4"><br/>
						Thank you for using Siam Commercial Bank Services!
                </td>
            
        </tr>
       
    </table>

</body>
</html>
