<p>&nbsp;</p>
<table style="width: 100%;">
<tbody>
<tr>
<td style="font-weight: bold;" colspan="2"><img style="height: 70px;" src = "../../../Images/logo.png" /><br /><br /></td>
</tr>
<tr>
<td style="font-weight: bold; font-size: 14pt;" colspan="2" align="center">CONTRACT FEE<br /><br /></td>
</tr>
<tr>
<td>Contract No</td>
<td>$contractno$</td>
</tr>
<tr>
<td>Transaction</td>
<td>$trantype$</td>
</tr>
<tr>
<td style="height: 5px;">&nbsp;</td>
</tr>
<tr>
<td style="font-weight: bold; font-size: 10pt;" colspan="2">FEE INFOMATION<hr /></td>
</tr>
<tr>
<td>Fee name</td>
<td>$fee$</td>
</tr>
<tr>
<td>Currency</td>
<td>$ccyid$</td>
</tr>
<tr>
<td>Fee payer</td>
<td>$payer$</td>
</tr>
<tr>
<td>Description</td>
<td>$desc$</td>
</tr>
<tr>
<td style="height: 5px;">&nbsp;</td>
</tr>
<tr>
<td style="font-weight: bold; font-size: 10pt;" colspan="2">MODIFICATION INFOMATION<hr /></td>
</tr>
<tr>
<td>Date created</td>
<td>$datecreated$</td>
</tr>
<tr>
<td>User created</td>
<td>$usercreated$</td>
</tr>
<tr>
<td>Date approved</td>
<td>$dateapproved$</td>
</tr>
<tr>
<td>User approved</td>
<td>$userapproved$</td>
</tr>
<tr>
<td colspan="2"><br /><hr />
<p><a href="https://www.scb.co.th/en/personal-banking.html" target="blank"></a></p>
<span style="font-weight: bold;"> Thank you for using services of Siam Commercial Bank! </span></td>
</tr>
</tbody>
</table>