<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Untitled Page</title>
</head>
<body>

    <table style="width:100%;">
		<tr>
			<td colspan="2" 
                style="font-weight: bold;">
             <img src='../../images/logo_y70.png' style='height:70px;' /><br/>             
             <br/></td>
		</tr>
		<tr>
			<td align="center" colspan="2" 
                style="font-weight: bold; font-size:14pt;">
               TRA SOÁT GIAO DỊCH<br/><br/></td>
		</tr>
        <tr>
			<td>Số giao dịch</td>
			<td>$transid$</td>
        </tr>
        <tr>
			<td style="height:5px;">
			
			</td>
        </tr>
        <tr>
            <td colspan="2" 
                style="font-weight: bold; font-size:10pt;">
                THÔNG TIN TRA SOÁT GIAO DỊCH<hr /></td>
        </tr>
        <tr>
			<td>Tiêu đề</td>
			<td>$title$</td>
        </tr>
        <tr>
			<td>Nội dung</td>
			<td>$content$</td>
        </tr>
        <tr>
			<td style="height:5px;">
			
			</td>
        </tr>
        <tr>
            <td colspan="2" 
                style="font-weight: bold; font-size:10pt;">
               PHẢN HỒI TỪ NGÂN HÀNG<hr /></td>
        </tr>
        <tr>
			<td>Trả lời</td>
			<td>$comment$</td>
        </tr>
        <tr>
			<td style="height:5px;">
			
			</td>
        </tr>
        </table>
			
        <table style="width:100%;">
       <tr>
			<td colspan="2">
				<br/>
				<hr/>
				<span style='font-size:8pt;'>
				<p><a href='https://www.Kasikorn.com' target='blank'>www.mKasikorn.com</a></p>
				<span style='font-weight:bold;'>
				Cảm ơn quý khách đã sử dụng dịch vụ ebanking của Kasikorn!
				</span>
			</td>
		</tr>
    </table>

</body>
</html>
