<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Untitled Page</title>
</head>
<body>

    <table style="width:100%;">
        <tr>
            <td align="center" colspan="4" 
                style="font-weight: bold; font-size: large; color: #FF0000">
                THÔNG TIN HỢP ĐỒNG<hr /></td>
        </tr>
        <tr>
            <td colspan="4" style="font-weight: bold; background-color: #C0C0C0;">
                CHI TIẾT KHÁCH HÀNG</td>
        </tr>
        <tr>
            <td>
                Mã khách hàng :</td>
            <td>
                $CUSTID$</td>
            <td>
                Tên khách hàng :</td>
            <td>
                $FULLNAME$</td>
        </tr>
        <tr>
            <td>
                Loại khách hàng :</td>
            <td>
                $CUSTTYPE$</td>
            <td>
                Điện thoại :</td>
            <td>
                $PHONE$</td>
        </tr>
        <tr>
            <td>
                Email :</td>
            <td>
                $EMAIL$</td>
            <td>
                &nbsp;</td>
            <td>
                &nbsp;</td>
        </tr>
        <tr>
            <td colspan="4" style="font-weight: bold; background-color: #C0C0C0;">
                CHI TIẾT HỢP ĐỒNG</td>
        </tr>
        <tr>
            <td>
                Số hợp đồng :</td>
            <td>
                $CONTRACTNO$</td>
            <td>
                Loại hợp đồng :</td>
            <td>
                $CONTRACTTYPE$</td>
        </tr>
        <tr>
            <td>
                Ngày mở :</td>
            <td>
                $OPENDATE$</td>
            <td>
                Ngày hết hạn :</td>
            <td>
                $ENDDATE$</td>
        </tr>
        <tr>
            <td>
                Loại hình :</td>
            <td>
                $PRODUCT$</td>
            <td>
                &nbsp;</td>
            <td>
                &nbsp;</td>
        </tr>
        <tr>
            <td colspan="4" style="font-weight: bold; background-color: #C0C0C0;">
                CHI TIẾT TÀI KHOẢN</td>
        </tr>
        <tr>
            <td colspan="4">
                $USERINFO$</td>
            
        </tr>
       
    </table>

</body>
</html>
