<html>

<head>
<meta http-equiv=Content-Type content="text/html; charset=us-ascii">
<meta name=Generator content="Microsoft Word 15 (filtered)">
</head>

<body lang=EN-US>

<div class=WordSection1>

<table border=0 cellpadding=0 width="100%"
 style='width:100.0%'>
 <tr>
  <td colspan=4 style='padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal align=center style='text-align:center'><b><span
  style='font-size:13.0pt;color:red'>CONTRACT INFORMATION</span></b></p>
  </td>
 </tr>
 <tr>
  <td colspan=4 style='background:silver;background-color: #C0C0C0; line-height:13px;'>
  <b>CUSTOMER DETAILS</b>
  </td>
 </tr>
 <tr>
  <td width="25%" style='width:25.0%;'>
  Customer id
  </td>
  <td width="25%" style='width:25.0%;'>
  $CUSTID$
  </td>
  <td width="25%" style='width:25.0%;'>
  Customer name
  </td>
  <td width="25%" style='width:25.0%;'>
  $FULLNAME$
  </td>
 </tr>
 <tr>
  <td>
  Customer type
  </td>
  <td>
  $CUSTTYPE$
  </td>
  <td>
  Phone
  </td>
  <td>
  $PHONE$
  </td>
 </tr>
 <tr>
  <td>
  Email 
  </td>
  <td colspan=3>
  $EMAIL$
  </td>
 </tr>
 <tr>
  <td colspan=4 style='line-height:5px;'>
  </td>
 </tr>
 <tr>
  <td colspan=4 style='background:silver;background-color: #C0C0C0; line-height:13px;'>
  <b>CONTRACT DETAILS</b>
  </td>
 </tr>
 <tr>
  <td width="25%" style='width:25.0%;'>
  Contract No 
  </td>
  <td width="25%" style='width:25.0%;'>
  $CONTRACTNO$
  </td>
  <td width="25%" style='width:25.0%;'>
  Contract type 
  </td>
  <td width="25%" style='width:25.0%;'>
  $CONTRACTTYPE$
  </td>
 </tr>
 <tr>
  <td>
  Open date 
  </td>
  <td>
  $OPENDATE$
  </td>
  <td>
  Expire date 
  </td>
  <td>
  $ENDDATE$
  </td>
 </tr>
 <tr>
  <td>
  Product type
  </td>
  <td colspan=3>
  $PRODUCT$
  </td>
 </tr>
 <tr>
  <td colspan="4">
  $USERINFO$</td>            
 </tr>  
 <tr>
  <td colspan="4">
  $NGUOIUYQUYEN$</td>            
 </tr>       
 <tr>
  <td colspan="4">
  $NUQ$</td>            
 </tr>       
 <tr>
  <td colspan="4">
  $LEVEL2$</td>            
 </tr>      
</table>
</body>
</html>
