<div>
<table style="width: 500pt; margin: 0;" border="0" cellspacing="0" cellpadding="0">
<tbody>
<tr>
<td style="border: solid #CCCCCC 1.0pt; border-bottom: none; padding: 5pt 14.25pt 0 14.25pt;">
<p><span style="font-size: 12.0pt;"> <img src = "https://upload.wikimedia.org/wikipedia/en/thumb/4/47/Siam_Commercial_Bank_%28logo%29.svg/345px-Siam_Commercial_Bank_%28logo%29.svg.png" width="270" height="100" /> </span></p>
</td>
</tr>
<tr>
<td style="border: solid #CCCCCC 1.0pt; border-top: none; padding: 0;">
<table style="width: 100%;" border="0" width="100%" cellspacing="0" cellpadding="0">
<tbody>
<tr>
<td style="padding: 11.25pt 14.25pt 11.25pt 14.25pt;">
<table style="width: 100%;" border="0" cellspacing="0" cellpadding="0">
<tbody>
<tr>
<td style="width: 57%;">
<p style="margin-bottom: 12.0pt; line-height: 14pt;"><span style="font-size: 9.0pt; font-family: 'Arial', 'sans-serif'; color: #333333;"> Dear Valued Customers, <br /><br />Your A PLUS service is ready for use: </span></p>
<ul>
<li><span style="font-size: 9.0pt; font-family: 'Arial', 'sans-serif'; color: #333333;">Contract No: $CONTRACTNO$</span></li>
<li><span style="font-size: 9.0pt; font-family: 'Arial', 'sans-serif'; color: #333333;">Email Address: $EMAIL$</span></li>
</ul>
<p style="line-height: 14pt;"><span style="font-size: 9.0pt; font-family: 'Arial', 'sans-serif'; color: #333333;"> <br />Please refer the attached to get Username and Password. <br /><br />Thank you for choosing Siam Commercial Bank. <br /><br />Kind regards, </span></p>
<p style="line-height: 14pt;"><strong> <span style="font-size: 9.0pt; font-family: 'Arial', 'sans-serif'; color: #4733a2;"> Siam Commercial Mobile Banking Department </span> </strong></p>
</td>
<td style="width: 3%;">&nbsp;</td>
<td style="width: 40%; background: #D9D9D9; padding: 7.5pt;">
<table border="0" cellpadding="1">
<tbody>
<tr>
<td><strong> <span style="font-size: 13pt; font-family: 'Arial', 'sans-serif'; color: #4733a2;"> How to log in to Siam Commercial Bank </span> </strong></td>
</tr>
<tr>
<td><strong> <span style="font-size: 12pt; font-family: 'Arial', 'sans-serif'; color: #333333;"> Step 1: </span> </strong></td>
</tr>
<tr>
<td><span style="font-size: 9.0pt; font-family: 'Arial', 'sans-serif'; color: #333333;"><span style="font-size: 9.0pt; font-family: 'Arial', 'sans-serif'; color: #333333;"> Download latest version of our mobile app. <br /></span></span>
<table style="width: 100%; font-size: 9.0pt; font-family: 'Arial', 'sans-serif'; color: #333333;" border="0" width="100%" cellspacing="0" cellpadding="0">
<tbody>
<tr>
<td>Android:</td>
<td><a style="text-decoration: none;" href="https://www.scb.co.th/en/personal-banking.html"><span style="font-size: 10.0pt; font-family: 'Arial', 'sans-serif'; color: #333333;">Coming soon</span></a></td>
</tr>
<tr>
<td>IOS:</td>
<td><a style="text-decoration: none;" href="https://www.scb.co.th/en/personal-banking.html"><span style="font-size: 10.0pt; font-family: 'Arial', 'sans-serif'; color: #333333;">Coming soon</span></a></td>
</tr>
</tbody>
</table>
</td>
</tr>
<tr>
<td><strong> <span style="font-size: 11pt; font-family: 'Arial', 'sans-serif'; color: #333333;"> Step 2: </span> </strong></td>
</tr>
<tr>
<td><span style="font-size: 9.0pt; font-family: 'Arial', 'sans-serif'; color: #333333;"> Enter your username and password from this email. </span></td>
</tr>
<tr>
<td><strong> <span style="font-size: 11pt; font-family: 'Arial', 'sans-serif'; color: #333333;"> Step 3: </span> </strong></td>
</tr>
<tr>
<td><span style="font-size: 9.0pt; font-family: 'Arial', 'sans-serif'; color: #333333;">Verify your identity. Then enter OTP received through your registered phone number. </span></td>
</tr>
<tr>
<td><strong> <span style="font-size: 11pt; font-family: 'Arial', 'sans-serif'; color: #333333;"> Step 4: </span> </strong></td>
</tr>
<tr>
<td><span style="font-size: 9.0pt; font-family: 'Arial', 'sans-serif'; color: #333333;">Set up new password and log in to new Siam Commercial Bank Plus.</span></td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
<tr>
<td style="background: #4733a2; padding: 10pt 14.25pt 10pt 14.25pt; text-align: right;"><strong> <a style="text-decoration: none;" href="https://www.scb.co.th/en/personal-banking.html"><span style="font-size: 10.0pt; font-family: 'Arial', 'sans-serif'; color: white;"> </span></a> </strong></td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
</div>