<p>&nbsp;</p>
<div class="WordSection1">
	<table style="width: 100.0%; font-size: 10px;" border="0" width="100%" cellpadding="0">
		<tbody>
			<tr>
				<td style="padding: 0.75pt; width: 98.2955%;" colspan="4">
					<p class="MsoNormal" style="text-align: center;" align="center">
						<strong>
							<span style="font-size: 13.0pt; color: red;">CONTRACT INFORMATION</span>
						</strong>
					</p>
				</td>
			</tr>
			<tr>
				<td style="background:silver;background-color: #C0C0C0; line-height:13px;" colspan="4">
					<strong>&nbsp;&nbsp;CUSTOMER DETAILS</strong>
				</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;">&nbsp;&nbsp;Customer id</td>
				<td style="width: 73.7216%;" colspan="3">&nbsp;&nbsp;$CUSTID$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;">&nbsp;&nbsp;Customer type</td>
				<td style="width: 24.5739%;">&nbsp;&nbsp;$CUSTTYPE$</td>
				<td style="width: 24.5739%;">&nbsp;&nbsp;Customer name</td>
				<td style="width: 24.5739%;">&nbsp;&nbsp;$FULLNAME$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;">&nbsp;&nbsp;Email</td>
				<td style="width: 24.5739%;">&nbsp;&nbsp;$EMAIL$</td>
				<td style="width: 24.5739%;">&nbsp;&nbsp;Phone</td>
				<td style="width: 24.5739%;">&nbsp;&nbsp;$PHONE$</td>
			</tr>
			<tr>
				<td style="line-height: 5px; width: 98.2955%;" colspan="4">&nbsp;</td>
			</tr>
			<tr>
				<td  style="background:silver;background-color: #C0C0C0; line-height:13px;" colspan="4">
					<strong>&nbsp;&nbsp;CONTRACT DETAILS</strong>
				</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;" width="25%">&nbsp;&nbsp;Contract No</td>
				<td style="width: 24.5739%;" width="25%">&nbsp;&nbsp;$CONTRACTNO$</td>
				<td style="width: 24.5739%;" width="25%">&nbsp;&nbsp;Contract type</td>
				<td style="width: 24.5739%;" width="25%">&nbsp;&nbsp;$CONTRACTTYPE$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;">&nbsp;&nbsp;Open date</td>
				<td style="width: 24.5739%;">&nbsp;&nbsp;$OPENDATE$</td>
				<td style="width: 24.5739%;">&nbsp;&nbsp;Expire date</td>
				<td style="width: 24.5739%;">&nbsp;&nbsp;$ENDDATE$</td>
			</tr>
			<tr>
				<td style="width: 24.5739%;">&nbsp;&nbsp;Product type</td>
				<td style="width: 73.7216%;" colspan="3">&nbsp;&nbsp;$PRODUCT$</td>
			</tr>
			<tr>
				<td style="width: 98.2955%;" colspan="4">$USERINFO$</td>
			</tr>
			<tr>
				<td style="width: 98.2955%;" colspan="4">$NGUOIUYQUYEN$</td>
			</tr>
			<tr>
				<td style="width: 98.2955%;" colspan="4">$NUQ$</td>
			</tr>
			<tr>
				<td style="width: 98.2955%;" colspan="4">$LEVEL2$</td>
			</tr>
		</tbody>
	</table>
</div>