//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3053.
// 
#pragma warning disable 1591

namespace PaymentInter.capnuoccholon {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getW_BillOperationCompleted;
        
        private System.Threading.SendOrPostCallback payW_BillOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCustomerInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::PaymentInter.Properties.Settings.Default.PaymentInter_capnuoccholon_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getW_BillCompletedEventHandler getW_BillCompleted;
        
        /// <remarks/>
        public event payW_BillCompletedEventHandler payW_BillCompleted;
        
        /// <remarks/>
        public event getCustomerInfoCompletedEventHandler getCustomerInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getW_Bill", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getW_Bill(string danhba, string ten, string matkhau) {
            object[] results = this.Invoke("getW_Bill", new object[] {
                        danhba,
                        ten,
                        matkhau});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getW_BillAsync(string danhba, string ten, string matkhau) {
            this.getW_BillAsync(danhba, ten, matkhau, null);
        }
        
        /// <remarks/>
        public void getW_BillAsync(string danhba, string ten, string matkhau, object userState) {
            if ((this.getW_BillOperationCompleted == null)) {
                this.getW_BillOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetW_BillOperationCompleted);
            }
            this.InvokeAsync("getW_Bill", new object[] {
                        danhba,
                        ten,
                        matkhau}, this.getW_BillOperationCompleted, userState);
        }
        
        private void OngetW_BillOperationCompleted(object arg) {
            if ((this.getW_BillCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getW_BillCompleted(this, new getW_BillCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/payW_Bill", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool payW_Bill(string id, string ten, string matkhau) {
            object[] results = this.Invoke("payW_Bill", new object[] {
                        id,
                        ten,
                        matkhau});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void payW_BillAsync(string id, string ten, string matkhau) {
            this.payW_BillAsync(id, ten, matkhau, null);
        }
        
        /// <remarks/>
        public void payW_BillAsync(string id, string ten, string matkhau, object userState) {
            if ((this.payW_BillOperationCompleted == null)) {
                this.payW_BillOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpayW_BillOperationCompleted);
            }
            this.InvokeAsync("payW_Bill", new object[] {
                        id,
                        ten,
                        matkhau}, this.payW_BillOperationCompleted, userState);
        }
        
        private void OnpayW_BillOperationCompleted(object arg) {
            if ((this.payW_BillCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.payW_BillCompleted(this, new payW_BillCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCustomerInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getCustomerInfo(string danhba, string ten, string matkhau) {
            object[] results = this.Invoke("getCustomerInfo", new object[] {
                        danhba,
                        ten,
                        matkhau});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getCustomerInfoAsync(string danhba, string ten, string matkhau) {
            this.getCustomerInfoAsync(danhba, ten, matkhau, null);
        }
        
        /// <remarks/>
        public void getCustomerInfoAsync(string danhba, string ten, string matkhau, object userState) {
            if ((this.getCustomerInfoOperationCompleted == null)) {
                this.getCustomerInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCustomerInfoOperationCompleted);
            }
            this.InvokeAsync("getCustomerInfo", new object[] {
                        danhba,
                        ten,
                        matkhau}, this.getCustomerInfoOperationCompleted, userState);
        }
        
        private void OngetCustomerInfoOperationCompleted(object arg) {
            if ((this.getCustomerInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCustomerInfoCompleted(this, new getCustomerInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void getW_BillCompletedEventHandler(object sender, getW_BillCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getW_BillCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getW_BillCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void payW_BillCompletedEventHandler(object sender, payW_BillCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class payW_BillCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal payW_BillCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void getCustomerInfoCompletedEventHandler(object sender, getCustomerInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCustomerInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCustomerInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591