<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Untitled Page</title>
</head>
<body>

    <table style="width:100%;">
		<tr>
			<td colspan="2" 
                style="font-weight: bold;">
             <img src='https://upload.wikimedia.org/wikipedia/en/thumb/4/47/Siam_Commercial_Bank_%28logo%29.svg/345px-Siam_Commercial_Bank_%28logo%29.svg.png' style='height:70px;' /><br/>             
             <br/></td>
		</tr>
		<tr>
			<td align="center" colspan="2" 
                style="font-weight: bold; font-size:14pt;">
               CHI TIẾT GIAO DỊCH LÔ<br/><br/></td>
		</tr>
        <tr>
			<td>Số giao dịch</td>
			<td>$transid$</td>
        </tr>
        <tr>
			<td style="height:5px;">
			
			</td>
        </tr>
        <tr>
            <td colspan="2" 
                style="font-weight: bold; font-size:10pt;">
                THÔNG TIN TÀI KHOẢN<hr /></td>
        </tr>
        <tr>
			<td>Tài khoản nguồn</td>
			<td>$senderaccount$</td>
        </tr>
        <tr>
			<td>Tên tài khoản</td>
			<td>$sender$</td>
        </tr>
        <tr>
			<td style="height:5px;">
			
			</td>
        </tr>
        <tr>
            <td colspan="2" 
                style="font-weight: bold; font-size:10pt;">
                NỘI DUNG THANH TOÁN<hr /></td>
        </tr>
        <tr>
			<td>Nội dung</td>
			<td>$content$</td>
        </tr>
        <tr>
			<td style="height:5px;">
			
			</td>
        </tr>
        
        </table>

			$batch$
		<table style="width:100%;margin-bottom:50px;margin-top:15px;">
					<tr>
						<td style="width:25%;text-align:center">
						KẾ TOÁN VIÊN
						</td>
						<td style="width:25%;text-align:center">
						KIỂM SOÁT VIÊN
						</td>
						<td style="width:25%;text-align:center">
						CHỦ TÀI KHOẢN
						</td>
						<td style="width:25%;text-align:center">
						NGƯỜI GỬI
						</td>
					</tr>
		</table>	
        <table style="width:100%;">
       <tr>
			<td colspan="2">
				<br/>
				<hr/>
				<span style='font-size:8pt;'>
				<p><a href='https://www.scb.co.th/en/personal-banking.html' target='blank'>www.scb.co.th/en/personal-banking</a></p>
				<span style='font-weight:bold;'>
				Cảm ơn quý khách đã sử dụng dịch vụ ebanking của Phongsavanh!
				</span>
			</td>
		</tr>
    </table>

</body>
</html>
