<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Untitled Page</title>

<style type="text/css">
<!--
.style1 {
	color: #0033FF;
	font-weight: bold;
}
.style2 {
	font-size: 18px;
	font-weight: bold;
}
-->
</style>
</head>

<body>
<p class="style1">Siam Commercial Bank</p>
  
<p>Hello : <span class="style2">$Username$</span> .System received your request about reset password, your new password is  : <span class="style2">$Password$</span><br />
  <br \>
  <a href="https://www.scb.co.th/en/personal-banking.html"></a><br />
    <br \>
  Thank you for using Siam Commercial eBanking Services!</p>
</body>
</html>
