<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Untitled Page</title>
</head>
<body>

    <table style="width:100%;">
       <tr>
            <td align="center" colspan="4" 
                style="font-weight: bold; font-size:11pt; color: #FF0000">
                THÔNG TIN TÀI KHOẢN<hr /></td>
        </tr>
        <tr>
            <td colspan="4" style="font-weight: bold; background-color: #C0C0C0;">
                CHI TIẾT TÀI KHOẢN</td>
        </tr>
        <tr>
            <td colspan="4">
                $USERINFO$</td>
            
        </tr>
       
    </table>

</body>
</html>
