<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Untitled Page</title>

<style type="text/css">
<!--
.style1 {
	color: #0033FF;
	font-weight: bold;
}
.style2 {
	font-size: 18px;
	font-weight: bold;
}
-->
</style>
</head>

<body>
<p class="style1">Siam Commercial Bank</p>

    <table style="width:100%;">
       <tr>
            <td align="center" colspan="4" 
                style="font-weight: bold; font-size: 11pt; color: #FF0000">
                INFORMATION PINCODE<hr /></td>
        </tr>
        <tr>
            <td colspan="4">
                Welcome <b>$FULLNAME$</b>. Username is <b>$USER$</b>. User type <b>$TYPEID$</b> <br />
                We received a request to reset your pincode for $SERVICE$ service  <br />
                Your new pincode is : <b>$PASS$</b>
                </td>
            
        </tr>
                <tr>
            <td colspan="4"><br/>
						Thank you for using Siam Commercial Bank Services!
                </td>
            
        </tr>
       
    </table>

</body>
</html>
