<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Untitled Page</title>
</head>
<body>

    <table style="width:100%;">
		<tr>
			<td colspan="2" 
                style="font-weight: bold;">
             <img src = '../../../Images/logo.png' style='height:70px;' /><br/>             
             <br/></td>
		</tr>
        </table>
        <table style="width:100%;">
        <tr>
			<td align="center" colspan="2" 
                style="font-weight: bold; font-size:14pt;">
                THÔNG TIN HẠN MỨC HỢP ĐỒNG<br/><br/></td>
		</tr>
        
        <tr>
			<td>Mã hợp đồng</td>
			<td>$contractno$</td>
        </tr>
        <tr>
			<td>Loại giao dịch</td>
			<td>$trantype$</td>
        </tr>
        <tr>
			<td>Hạn mức / giao dịch</td>
			<td>$tranlimit$</td>
        </tr>
        <tr>
			<td>Tổng hạn mức / ngày</td>
			<td>$totallimitday$ </td>
        </tr>
        <tr>
			<td>Số giao dịch / ngày</td>
			<td>$countlimit$</td>
        </tr>
        <tr>
			<td>Loại tiền tệ</td>
			<td>$ccyid$</td>
        </tr>
        <tr>
			<td>Người tạo</td>
			<td>$usercreated$</td>
        </tr>
        <tr>
			<td>Ngày tạo</td>
			<td>$datecreated$</td>
        </tr>
        <tr>
			<td>Người duyệt</td>
			<td>$userapproved$</td>
        </tr>  
        <tr>
			<td>Ngày duyệt</td>
			<td>$dateapproved$</td>
        </tr>
        </table>
			</td>
		</tr>
       <tr>
			<td colspan="2">
				<br/>
				<p><a href='https://www.scb.co.th/en/personal-banking.html' target='blank'></a></p>
				<span style='font-weight:bold;'>
				Cảm ơn quý khách đã sử dụng dịch vụ ebanking của Siam Commercial Bank!
				</span>
			</td>
		</tr>
    </table>

</body>
</html>
