<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Untitled Page</title>
</head>
<body>

    <table style="width:100%;">
		<tr>
			<td colspan="2" 
                style="font-weight: bold;">
           <img src="https://ib.hellomoney.com.la:9004/Images/logo.png" /><br/>             
             <br/></td>
		</tr>
		<tr>
			<td align="center" colspan="2" 
                style="font-weight: bold; font-size:14pt;">
                REQUEST EXPORT STATEMENT<br/><br/></td>
		</tr>
		<tr>
			<td>Date time</td>
			<td>$tranDate$</td>
        </tr>
        <tr>
			<td style="height:5px;">
			
			</td>
        </tr>
        <tr>
            <td colspan="2" 
                style="font-weight: bold; font-size:10pt;">
                SENDER INFOMATION<hr /></td>
        </tr>
        <tr>
              <td>Sender name</td>
			<td>$senderName$</td>
        </tr>
        <tr>
			<td>Debit account</td>
			<td>$senderAccount$</td>
        </tr>   
        <tr>
			<td>User Name</td>
			<td>$userid$</td>
        </tr> 
                <tr>
			<td>Phone Number</td>
			<td>$phone$</td>
        </tr> 
          <tr>
			<td>Serial No</td>
			<td>$serialno$</td>
        </tr> 
           <tr>
			<td>Statement Version</td>
			<td>$version$</td>
        </tr>     
        <tr>
			<td>Purpose of Request Statement</td>
			<td>$purpose$</td>
        </tr>
          <tr>
			<td>Detail</td>
			<td>$detail$</td>
        </tr>
        <tr>
			<td>Email</td>
			<td>$email$</td>
        </tr>
        <tr>
			<td style="height:5px;">
			
			</td>
        </tr>
        <tr>
            <td colspan="2" 
                style="font-weight: bold; font-size:10pt;">
                REQUEST STATEMENT TIME<hr /></td>
        </tr>
        <tr>
			<td>From date</td>
			<td>$fromdate$</td>
        </tr>
        <tr>
			<td>To date</td>
			<td>$todate$</td>
        </tr>        
        
       <tr>
			<td colspan="2">
				<br/>
				<hr/>
				<p><a href='https://www.phongsavanhbank.com/' target='blank'>https://www.phongsavanhbank.com/</a></p>
				<span style='font-weight:bold;'>
				Thank you for using services of PSV Bank!
				</span>
			</td>
		</tr>
    </table>

</body>
</html>
