<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <style>
        table, th, td {
            border: 1px solid black;
            border-collapse: collapse;
        }

        body {
            margin-top: 20px;
            margin-bottom: 50px;
            margin-right: 50px;
            margin-left: 40px;
            font-size: 15px
        }
    </style>
</head>
<body>
    <h3>Request export statement</h3>
    <img width="100%" height="50%" src="https://www.phongsavanhbank.com/psv/allpages/lao/img/pro_psv16years_and_apa.jpg" />
    <h4 style="color:#28a745 !important">1. I have read and agree with following Terms and Conditions</h4>
    <ul>
        <li>You are authorizing SIAM COMMERCIAL BANK to deliver statements of your account(s) by electronic means and agree that electronic delivery will satisfy Siam Commercial Bank’s requirement to provide you a periodic statement of your account(s) activity.</li>
        <li>The statement will be sent to only one e‐mail address which appears in the above screen and you are ensure that your above email has been encrypted by passwords.</li>
        <li>
            You agree to protect the confidentiality of your account, account number, usernames and
            passwords. You agree that it is your responsibility to ensure that the electronic statements are not intercepted or viewed by others and for ensuring that you have logged out when your session is complete to prevent unauthorized access. It is your responsibility to contact and inform the bank if you know or suspect unauthorized use of your User ID and Password
            .
        </li>
        <li>You agree that the bank has no control as to the persons who have access to your personal computer or mobile and your password once it is in your possession. The bank will not be liable for any unauthorized access to my personal computer or mobile or my passwords</li>
        <li>If your electronic mail is returned as undeliverable a reasonable attempt will be made to contact you.  Users of Online Banking are responsible for providing the bank with up‐to‐date contact information</li>
        <li>I agree to pay the fee for requesting this account statement by electronic mean at a charge of $fee$..LAK per statement </li>
        <li>You confirm that you will use this account statement in the purpose of which has been ticked above by you and If there are any damages/loses occurred in relation of using this statement, you will take full responsibility to the damages.</li>
    </ul>
    The Customer agree to abide by the Terms and Conditions and other terms and conditions as available on the Website <a href="https://www.phongsavanhbank.com/psv/modules.php?lg=eng&modules=deposit_acc&acc=acc-fix2">https://www.phongsavanhbank.com</a> including but not limited to the charges, interests applicable in relation to the fixed deposit,
    charges applicable in case of premature withdrawal of an fixed deposit.
</body>
The End
</html>
